# Generated by Django 4.2.3 on 2023-09-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pvp',
            new_name='price',
        ),
    ]
